#application: ffadocuments
#version: 10
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js
  
- url: /css
  static_dir: css

- url: /.*
  script: main.app
  login: admin

- url: /tasks/calgen
  script: calgen.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.1"

builtins:
- remote_api: on